### ISSUE TITLE
Changes in PR #48 break backward compat?

### ISSUE THREAD

**Issue by nrocy** [Codeception/lib-innerbrowser#49]
PR #48 replaced deprecated calls to `parents()` with `ancestors()` but this project package.json seems to allow for symfony/dom-crawler 4.4: `^4.4 | ^5.4 | ^6.0`

The ancestors() function wasn't added to dom-crawler until 5.3.0-BETA-1 so this seems to be a backward-compat breaking change.

Happy to help assist fix this as it's breaking our tests, how would you prefer to resolve it?

Thanks!

/cc @TavoNiievez

**Comment by TavoNiievez** [comment]
@nrocy your report is valid.

we'll probably have to use `method_exists()` before using `ancestors()`, otherwise use `parents()`

**Comment by TavoNiievez** [comment]
If you have time please open a PR for this and tag me to merge ASAP

**Comment by simonhammes** [comment]
See https://github.com/Codeception/lib-innerbrowser/pull/41
