### ISSUE TITLE
Interface "Codeception\Lib\Interfaces\Web" not found 

### ISSUE THREAD

**Issue by bloodrain777** [Codeception/lib-innerbrowser#62]
Interface "Codeception\Lib\Interfaces\Web" not found  in /app/vendor/codeception/lib-innerbrowser/src/Codeception/Lib/InnerBrowser.php:43

`
root@7e8acfb44d18:/app# composer show -i | grep codeception
`
codeception/codeception                      5.0.0               BDD-style testing framework
codeception/lib-asserts                      2.0.1               Assertion methods used by Codeception core and Asserts module
codeception/lib-innerbrowser                 3.0.1               Parent library for all Codeception framework modules and PhpBrowser
codeception/module-asserts                   3.0.0               Codeception module containing various assertions
codeception/module-filesystem                3.0.0               Codeception module for testing local filesystem
codeception/module-yii2                      1.1.7               Codeception module for Yii2 framework
codeception/stub                             4.0.2               Flexible Stub wrapper for PHPUnit's Mock Builder
codeception/verify                           2.3.0               BDD assertion library for PHPUnit

./vendor/bin/codeception run unit

`
Fatal error: Uncaught Error: Interface "Codeception\Lib\Interfaces\Web" not found in /app/vendor/codeception/lib-innerbrowser/src/Codeception/Lib/InnerBrowser.php:43
Stack trace:
#0 /app/vendor/composer/ClassLoader.php(582): include()
#1 /app/vendor/composer/ClassLoader.php(433): Composer\Autoload\{closure}('/app/vendor/com...')
#2 /app/vendor/codeception/lib-innerbrowser/src/Codeception/Lib/Framework.php(12): Composer\Autoload\ClassLoader->loadClass('Codeception\\Lib...')
#3 /app/vendor/composer/ClassLoader.php(582): include('/app/vendor/cod...')
#4 /app/vendor/composer/ClassLoader.php(433): Composer\Autoload\{closure}('/app/vendor/com...')
#5 /app/vendor/codeception/module-yii2/src/Codeception/Module/Yii2.php(169): Composer\Autoload\ClassLoader->loadClass('Codeception\\Lib...')
#6 /app/vendor/composer/ClassLoader.php(582): include('/app/vendor/cod...')
#7 /app/vendor/composer/ClassLoader.php(433): Composer\Autoload\{closure}('/app/vendor/com...')
#8 [internal function]: Composer\Autoload\ClassLoader->loadClass('Codeception\\Mod...')
#9 /app/vendor/codeception/codeception/src/Codeception/Lib/ModuleContainer.php(97): class_exists('\\Codeception\\Mo...')
#10 /app/vendor/codeception/codeception/src/Codeception/SuiteManager.php(49): Codeception\Lib\ModuleContainer->create('Yii2')
#11 /app/vendor/codeception/codeception/src/Codeception/Codecept.php(255): Codeception\SuiteManager->__construct(Object(Symfony\Component\EventDispatcher\EventDispatcher), 'unit', Array, Array)
#12 /app/vendor/codeception/codeception/src/Codeception/Codecept.php(216): Codeception\Codecept->runSuite(Array, 'unit', NULL)
#13 /app/vendor/codeception/codeception/src/Codeception/Command/Run.php(653): Codeception\Codecept->run('unit')
#14 /app/vendor/codeception/codeception/src/Codeception/Command/Run.php(474): Codeception\Command\Run->runSuites(Array, Array)
#15 /app/vendor/symfony/console/Command/Command.php(312): Codeception\Command\Run->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /app/vendor/symfony/console/Application.php(1022): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /app/vendor/symfony/console/Application.php(314): Symfony\Component\Console\Application->doRunCommand(Object(Codeception\Command\Run), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /app/vendor/symfony/console/Application.php(168): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /app/vendor/codeception/codeception/src/Codeception/Application.php(112): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /app/vendor/codeception/codeception/app.php(45): Codeception\Application->run()
#21 /app/vendor/codeception/codeception/app.php(46): {closure}()
#22 /app/vendor/codeception/codeception/codecept(7): require('/app/vendor/cod...')
#23 /app/vendor/bin/codecept(120): include('/app/vendor/cod...')
#24 {main}

`

**Comment by Naktibalda** [comment]
codeception/lib-innerbrowser 3.0.1 is old, upgrade to 3.1.* or 4.0.0 (4.0.0 works with PHPUnit 10 only).

If you are using Codeception 5, you should upgrade it to 5.0.10

**Comment by bloodrain777** [comment]
Thank you very much, I went to look for the problem in dependencies
