### ISSUE TITLE
Delete header vs unsetHttpHeader vs unsetHeader

### ISSUE THREAD

**Issue by mal-risma** [Codeception/lib-innerbrowser#73]
Calling deleteHeader gives an error because it tries to call unsetHttpHeader, but the function was renamed to unsetHeader. 

It doesn't matter in my tests if I call unsetHttpHeader or deleteHeader as I always endup in the deleteHeader function in InnerBrowser. 

The error is pretty obvious from this commit: 

https://github.com/Codeception/lib-innerbrowser/commit/66f06c9c627b00193f58de97d02cb7e1f83f91ae

I would make a PR, but I'm not sure what the correct fix is? 
Rename unsetHeader to unsetHttpHeader or just call unsetHeader instead of unsetHttpHeader from the deleteHeader function?

**Comment by Naktibalda** [comment]
Fixed in 4.0.5
